version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test-netcore-2-1
      - test-windows-netframework-4-5-2

orbs:
  win: circleci/windows@1.0.0

jobs:
  test-netcore-2-1:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1-focal
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
    steps:
      - checkout
      - restore_cache:
          keys: 
            - netcore20-deps-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}-{{ checksum "test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj" }}
      - run:
          name: install project dependencies
          command: dotnet restore
      - save_cache:
          key: netcore20-deps-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}-{{ checksum "test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj" }}
          paths:
            - /root/.nuget/packages
      - run:
          name: build SDK for .NET Standard 2.0
          command: dotnet build src/LaunchDarkly.CommonSdk -f netstandard2.0
      - run:
          name: run tests in .NET Core 2.0
          command: dotnet test test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj -f netcoreapp2.1
      - run:
          name: verify that both CommonSdk assemblies contain the same types
          command: ./packaging-test/compare-assembly-contents.sh netstandard2.0

  test-windows-netframework-4-5-2:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys: 
            - net452-deps-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}-{{ checksum "test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj" }}
      - run:
          name: install project dependencies
          command: dotnet restore
      - save_cache:
          key: net452-deps-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}-{{ checksum "test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj" }}
          paths:
            - C:\Users\circleci\.nuget\packages
      - run:
          name: build SDK for .NET Framework 4.5.2
          command: dotnet build src/LaunchDarkly.CommonSdk -f net452
      - run:
          name: run tests in .NET Framework 4.6
          command: dotnet test test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj -f net46
