repo:
  public: dotnet-sdk-common
  private: dotnet-sdk-common-private

releasableBranches:
  - name: master
    description: 5.x - for Xamarin 2.0+ and .NET 6.0+
  - name: 4.x
    description: for Xamarin 1.x
  - name: 2.x
    description: for current .NET SDK

publications:
  - url: https://nuget.org/packages/LaunchDarkly.CommonSdk
    description: NuGet (non-strong-named package)
  - url: https://nuget.org/packages/LaunchDarkly.CommonSdk.StrongName
    description: NuGet (strong-named package)

circleci:
  windows:
    context: org-global

template:
  name: dotnet-windows

# Note that we don't generate HTML docs for this project, because it's mostly internal stuff and the
# public stuff will be included in the API docs for the actual SDKs.
